model: 'GATGraphReg'
num_layers: 16
hidden_dim: 22
hidden_out_dim: 176
residual: True
batch_norm: True
readout: 'mean'
num_heads: 8
batch_size: 128
epochs: 1000
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: False
count_type: 'none'
count_files: ['zinc_with_homs_c7.json']
idx_list: []
description: 'standard GAT 500k'
