model: 'GINGraphReg'
num_layers: 16
hidden_dim: 124
residual: True
batch_norm: True
readout: 'sum'
batch_size: 128
epochs: 1000
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: True
count_type: 'both'
count_files: ['zinc_with_homs_c7.json', 'zinc_with_homs_c8.json']
idx_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 , 11, 15, 20, 21, 22, 24, 25, 27, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46]
description: 'GIN-500k with 78 cycle basis and multhom sum'