model: 'GCNGraphReg'
num_layers: 4
hidden_dim: 145
residual: True
batch_norm: True
readout: 'mean'
batch_size: 128
epochs: 1000
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: True
count_type: 'subcounts'
count_files: ['zinc_3to10C_subgraph.json']
idx_list: [5]
description: 'GCN-100k with only C8 subgraph cycles'
