model_name: 'SAGE'
project: 'collab-SAGE-PE'
group: 'SAGE-clique3-PE'
name: 'SAGE-clique3-PE'
use_counts: True
count_files: ['collab_path4_counts.json']
idx_list: [2]
pe_dim: 6
description: '3 clique, positional encoding'