model_name: 'SAGE'
project: 'collab-SAGE-PE'
group: 'SAGE-clique5-PE'
name: 'SAGE-clique5-PE'
use_counts: True
count_files: ['collab_clique5_counts.json']
idx_list: []
description: '5 clique, positional encoding'