model: 'GCNGraphReg'
num_layers: 4
hidden_dim: 145
residual: True
batch_norm: True
readout: 'mean'
batch_size: 128
epochs: 1000
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: True
count_type: 'homcounts'
count_files: ['with_homs_c8.json']
idx_list: []
description: '100% full basis for 8cycle GCN-100k'
