model_name: 'GAT'
project: 'collab-GAT-PE'
group: 'GAT-clique4-GAT-PE'
name: 'GAT-clique4-GAT-PE'
use_counts: True
count_files: ['collab_clique4_counts.json']
idx_list: []
pe_dim: 8
description: '4 clique, positional encoding'
