model: 'GATGraphReg'
num_layers: 4
hidden_dim: 18
hidden_out_dim: 144
residual: True
batch_norm: True
readout: 'mean'
num_heads: 8
batch_size: 128
epochs: 1000
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: True
count_type: 'both'
count_files: ['zinc_with_anchored_homs_c78_full.json']
idx_list: []
description: 'GAT-100k with anchored 78 cycle basis and subcounts'
