model: 'GCNGraphReg'
num_layers: 4
hidden_dim: 145
residual: True
batch_norm: True
readout: 'mean'
batch_size: 128
epochs: 1000
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: True
count_type: 'homcounts'
count_files: ['zinc_with_homs_c7.json', 'zinc_with_homs_c8.json']
idx_list: [0, 3, 11, 15, 31, 46]
description: 'GCN-100k only hom cycles up to 8'
