model: 'GCNGraphReg'
num_layers: 4
hidden_dim: 145
residual: True
batch_norm: True
readout: 'mean'
batch_size: 128
epochs: 1000
init_lr: .001
lr_factor: 0.5
lr_patience: 10
min_lr: .00001
use_counts: False
count_type: 'none'
count_files: ['zinc_with_homs_c7.json']
idx_list: []
description: 'standard GCN 100k'
